# Generated by Django 5.1.5 on 2025-01-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autonews',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usernews',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
